server:
  port: 8888
spring:
  application:
    name: zato
  datasource:
    url: jdbc:postgresql://localhost:9999/pokemon_db
    username: admin
    password: admin
  jpa:
#    hibernate:
#      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration